export const data = [
  {
    destination: "Бишкек",
    arrival: "Ош",
    selected: "2023-10-18",
    arrivalDate: "2023-10-19",
    amount: 4,
    driver: "Кубатбек",
    carName: "Хонда",
    model: "Элизон",
    price: 2000,
    time: "20:00",
    timeArrival: "11:00",
    driverImg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfSSz7czT2Ex0mj6B3J0uS6gOmsmnUr6yqzg&usqp=CAU",
    carImg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmpkMLT6nebLR5d2xkqEbOk7x1o0Oiu5fTsg&usqp=CAU",
  },
  {
    destination: "Бишкек",
    arrival: "Чолпон-Ата",
    selected: "2023-10-18",
    arrivalDate: "2023-10-20",
    amount: 4,
    driver: "Русланбек",
    carName: "Мерседес",
    model: "Бенз 2005",
    price: 3000,
    time: "20:00",
    timeArrival: "21:00",
    driverImg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfSSz7czT2Ex0mj6B3J0uS6gOmsmnUr6yqzg&usqp=CAU",
    carImg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyw5bKRLKodmY_Em-p8ttAQlEVD6ylWA0pKA&usqp=CAU"
  },
  {
    destination: "Бишкек",
    arrival: "Каракол",
    selected: "2023-10-18",
    arrivalDate: "2023-10-19",
    amount: 4,
    driver: "Элдосбек",
    carName: "Тойота",
    model: "Супра 2012",
    price: 2400,
    time: "08:00",
    timeArrival: "13:00",
    driverImg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfSSz7czT2Ex0mj6B3J0uS6gOmsmnUr6yqzg&usqp=CAU",
    carImg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShct0-tbkGFPfU8_kxLECJsL2vj-g9aWWdYw&usqp=CAU"
  },
];
